[package]
name = "drydock"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Fisher Darling <fdarlinco@gmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "./src/bin/main.rs"


[dependencies]
actix-web = "0.7.*"
